spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/DB/db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        #default_batch_fetch_size: 100
        #spring.jpa.open-in-view: false
        use_sql_comments: true

  jackson:
    property-naming-strategy: LOWER_CASE

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
